const $=id=>document.getElementById(id);
const homes=[{id:'0241',address:'Rua São Vicente, 120',lat:-7.0736,lng:-41.4676,status:'CONECTADO'},{id:'0242',address:'Rua São Vicente, 156',lat:-7.074,lng:-41.4672,status:'PENDENTE'},{id:'0243',address:'Rua São Vicente, 198',lat:-7.0744,lng:-41.4667,status:'PENDENTE'},{id:'0244',address:'Av. Nossa Senhora, 35',lat:-7.0754,lng:-41.4685,status:'CONECTADO'},{id:'0245',address:'Rua do Mercado, 18',lat:-7.0772,lng:-41.4669,status:'PENDENTE'},{id:'0246',address:'Rua da Paz, 58',lat:-7.0793,lng:-41.4674,status:'CONECTADO'}];
const incidents=[{id:'OC-01',type:'Esgoto a céu aberto',lat:-7.0768,lng:-41.4663},{id:'OC-02',type:'Descarte irregular',lat:-7.0783,lng:-41.4659}];let requests=18,connections=9;
const map=L.map('map').setView([-7.0765,-41.4671],16);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);const layers={network:L.layerGroup().addTo(map),homes:L.layerGroup().addTo(map),pending:L.layerGroup().addTo(map),incidents:L.layerGroup().addTo(map)};L.polyline([[-7.0729,-41.4682],[-7.0752,-41.4667],[-7.0776,-41.4658],[-7.0803,-41.4667]],{color:'#167c91',weight:6}).addTo(layers.network);
function showHome(home){$('selectedCard').innerHTML=`<h2>Domicílio #${home.id}</h2><p><b>Endereço:</b> ${home.address}</p><p><b>Rede:</b> disponível</p><p><b>Conexão:</b> ${home.status}</p>${home.status==='PENDENTE'?'<button class="primary" onclick="requestConnection()">Iniciar conexão</button>':''}`;map.setView([home.lat,home.lng],17)}function markerHome(home){const marker=L.circleMarker([home.lat,home.lng],{radius:8,color:'#fff',weight:2,fillColor:home.status==='CONECTADO'?'#4a9b58':'#d8931d',fillOpacity:.95}).bindPopup(`<b>Domicílio #${home.id}</b><br>${home.address}<br>${home.status}`);marker.on('click',()=>showHome(home));return marker}homes.forEach(home=>(home.status==='PENDENTE'?layers.pending:layers.homes).addLayer(markerHome(home)));incidents.forEach(item=>layers.incidents.addLayer(L.circleMarker([item.lat,item.lng],{radius:9,color:'#fff',fillColor:'#c94a45',fillOpacity:.95}).bindPopup(`<b>${item.type}</b>`)));
function refresh(){ $('statMapped').textContent=homes.length;$('statPending').textContent=homes.filter(h=>h.status==='PENDENTE').length;$('statIncidents').textContent=incidents.length;$('statRequests').textContent=requests;$('kpiMapped').textContent=homes.length*10+7;$('kpiPending').textContent=homes.filter(h=>h.status==='PENDENTE').length*3;$('kpiIncidents').textContent=incidents.length*2;$('kpiRequests').textContent=requests;$('kpiConversion').textContent=Math.round(connections/requests*100)+'%'}refresh();
['Network','Homes','Pending','Incidents'].forEach(name=>$("layer"+name).addEventListener('change',e=>{const layer=layers[name.toLowerCase()];e.target.checked?map.addLayer(layer):map.removeLayer(layer)}));$('search').addEventListener('input',e=>{const q=e.target.value.toLowerCase();const home=homes.find(h=>h.id.includes(q)||h.address.toLowerCase().includes(q));if(home)showHome(home)});
document.querySelectorAll('.tab').forEach(tab=>tab.addEventListener('click',()=>{document.querySelectorAll('.tab').forEach(item=>item.classList.remove('active'));tab.classList.add('active');document.querySelectorAll('.page').forEach(page=>page.classList.remove('active-page'));$('page-'+tab.dataset.tab).classList.add('active-page');if(tab.dataset.tab==='map')setTimeout(()=>map.invalidateSize(),100);refresh()}));
$('btnConsultar').addEventListener('click',()=>{if(!$('cpfInput').value.trim())return alert('Informe um CPF ou NIS.');const home=homes.find(h=>h.status==='PENDENTE');$('resAddress').textContent=home.address;$('resRede').textContent='Disponível';$('resConexao').textContent='Pendente';$('resTarifa').textContent='Potencialmente elegível';$('resEconomia').textContent='R$ 28,00/mês';$('resultBox').classList.remove('hidden');$('btnSolicitar').disabled=false});$('btnSolicitar').addEventListener('click',async()=>{const client=window.GuaribasRealtime?.client;const sessionResult=client?await client.auth.getSession():{data:{session:null}};const session=sessionResult.data.session;if(!session)return alert('Entre na sua conta antes de solicitar uma ligação.');const home=homes.find(h=>h.status==='PENDENTE');const protocol='GL-'+Date.now().toString().slice(-8);const {error}=await client.from('solicitacoes').insert({protocolo:protocol,domicilio_id:home.id,created_by:session.user.id});if(error)return alert('Não foi possível salvar a solicitação: '+error.message);requests++;connections++;$('protocolNumber').textContent=protocol;$('protocolBox').classList.remove('hidden');$('btnSolicitar').disabled=true;refresh()});window.requestConnection=()=>{requests++;connections++;refresh();alert('Solicitação demonstrativa registrada.');};
